---
#=========================================#
# Plugin Custom NPC Made By HighestDreams #
#=========================================#
name: CustomNPC
author: HighestDreams
mcpe-protocol: [361, 388, 389, 390, 407, 408, 440, 448]
version: 1.0.0
main: HighestDreams\CustomNPC\NPC
api: 3.0.0
commands:
  rca:
    description: Run a command from a player
    permission: customnpc.rca.permission
    usage: /rca <player-name> <command-for-execute)
  npc:
    description: Spawn custom npc
    permission: customnpc.permission

permissions:
  customnpc.rca.permission:
    description: "Allows the user to use /rca command"
    default: op
  customnpc.permission:
    description: "Allows the user to use /npc command (To spawn NPC & Edit NPC)"
    default: op
...
